# Generated by Django 3.2.5 on 2021-07-24 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('cand_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='backend.participant')),
                ('int_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='backend.participant')),
            ],
        ),
    ]
